import type { Metadata } from "next";
import { slugToBusinessName } from "@/lib/subdomain";
import DemoStorefront from "./DemoStorefront";

interface Params {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { slug } = await params;
  const businessName = slugToBusinessName(slug);
  return {
    title: `${businessName} — Demo Preview | Firewood Website`,
    description: `A personalized demo storefront preview for ${businessName}, generated by Firewood Website.`,
    robots: { index: false, follow: false },
  };
}

export default async function DemoPage({ params }: Params) {
  const { slug } = await params;
  const businessName = slugToBusinessName(slug);
  return <DemoStorefront slug={slug} businessName={businessName} />;
}
